all:
	cd libtcg && make $@
	cd pagestream && make $@
	cd rdllinjection && make $@
	cd simple_obj && make $@
	cd simple_objmix && make $@
	cd simple_pic && make $@
	cd simple_rdll && make $@
	cd simple_rdll_free && make $@
	cd simple_rdll_mask && make $@
	cd simple_rdll_patch && make $@
	cd simple_guardrail && make $@
	cd simple_rdll_hook && make $@
	cd simple_rdll_hook/modules/xorhooks && make $@
	cd simple_rdll_hook/modules/stackcutting && make $@

clean:
	cd libtcg && make $@
	cd pagestream && make $@
	cd rdllinjection && make $@
	cd simple_obj && make $@
	cd simple_objmix && make $@
	cd simple_pic && make $@
	cd simple_rdll && make $@
	cd simple_rdll_free && make $@
	cd simple_rdll_mask && make $@
	cd simple_rdll_patch && make $@
	cd simple_guardrail && make $@
	cd simple_rdll_hook && make $@
	cd simple_rdll_hook/modules/xorhooks && make $@
	cd simple_rdll_hook/modules/stackcutting && make $@
